val countries = listOf(
    "Åland",
    "American Samoa",
    "Andorra",
    "Anguilla",
    "Antarctica",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bangladesh",
    "Belarus",
    "Belgium",
    "Belize",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Botswana",
    "Brazil",
    "British Indian Ocean",
    "Brunei",
    "Bulgaria",
    "Cambodia",
    "Canada",
    "Chile",
    "China",
    "Colombia",
    "Cook Islands",
    "Croatia",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "East Timor",
    "Ecuador",
    "Egypt",
    "Estonia",
    "Falkland Islands",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Guadeloupe",
    "Guam",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Laos",
    "Latvia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Macau",
    "Madagascar",
    "Malaysia",
    "Maldives",
    "Martinique",
    "Mexico",
    "Midway Islands",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Northern Mariana Islands",
    "Norway",
    "Pakistan",
    "Palestine",
    "Panama",
    "Peru",
    "Philippines",
    "Pitcairn Islands",
    "Poland",
    "Portugal",
    "Qatar",
    "Réunion",
    "Romania",
    "Russia",
    "Saint Vincent & Grenadines",
    "San Marino",
    "Saudi Arabia",
    "Serbia",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "Sandwich Islands (SGSSI)",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "The Bahamas",
    "Turks and Caicos Islands",
    "Turkey",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Vietnam"
)